services:
  backend:
    image: gledsonlscruz/backend-protege-saude:v1.2.0
    container_name: backend-protege-saude
    pull_policy: always
    env_file:
      - .env
    ports:
      - "8080:8080"
    restart: unless-stopped
    volumes:
      - denuncias_data:/app/data

  frontend:
    image: gledsonlscruz/frontend-protege-saude:v1.2.0
    container_name: frontend-protege-saude
    pull_policy: always
    ports:
      - "3000:80"
    restart: unless-stopped
    depends_on:
      - backend

  admin:
    image: gledsonlscruz/admin-protege-saude:v1.2.0
    container_name: admin-protege-saude
    pull_policy: always
    ports:
      - "3001:80"
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  denuncias_data:
